name: CI Pipeline - Docker Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:

      - name: Step 1 - Checkout source code
        uses: actions/checkout@v4

      - name: Docker Set-up 
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Step 3- Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/real-devops:${{ github.sha }} .

      - name: Step 4- Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/real-devops:${{ github.sha }}
          
      - name: Step 5 - Success !!!
        if: success()
        run: echo "Docker image built and pushed successfully."
